spring.application.name=literalura

# Configuración de la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/literatura
spring.datasource.username=postgres
spring.datasource.password=Wixo1569.
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración para que Hibernate cree las tablas por ti
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true